package hxrm.generator.extensions;

import hxrm.analyzer.NodeScope;
import haxe.macro.Expr;

class ConstructorGeneratorExtension extends GeneratorExtensionBase {

	override public function generate(scope:NodeScope, type:TypeDefinition, pos:Position):Bool {
		if(getCtor(type) == null) {
			type.fields.push(generateCtor(pos));
		}
		
		return false;
	}

	function generateCtor(pos : Position):Field
	{
		var ctorExpr = macro { super(); };

		return {
			name: "new",
			doc: "autogenerated constructor",
			access: [APublic],
			pos: pos,
			kind: FFun({args:[], ret:null, expr:ctorExpr, params:[]})
		}
	}


}
